int *((((((((*j))))))));
int * (*((((((((*(((((*foo)))))(char)))))))))(double))[3];
int (i);
int (arr[4])[3];
int * const arr[3];
int (* arr)[3];
int * (*(*(*foo)(char))(double))[3];
int * (*(*(*foo)(char, int * (*(*(*d)(char))(double))[3], struct foo *))(double))[3];
int * (*(*(*(*(*b)[4])(float))(char))(double))[3];
int arr[2][3][4];
int (*p)[4];
int (*f(char))(float);
extern volatile signed long long g(int);
extern volatile signed long long * const * k;
extern volatile signed long long (*f(double))[];